export const ActionsType = {
  PATIENTS_LIST: 'PATIENTS_LIST',
  TOGGLE_ADD_PATIENT_MODAL: 'TOGGLE_ADD_PATIENT_MODAL',
  TOGGLE_PATIENT_DETAILS_MODAL: 'TOGGLE_PATIENT_DETAILS_MODAL',
  UPDATE_ADD_PATIENT_MODAL_STATE: 'UPDATE_ADD_PATIENT_MODAL_STATE',
  UPDATE_ACTIVE_USER_ID: 'UPDATE_ACTIVE_USER_ID',
};
