export const ActionsType = {
  DOCTORS_LIST: 'DOCTORS_LIST',
  TOGGLE_ADD_DOCTOR_MODAL: 'TOGGLE_ADD_DOCTOR_MODAL',
  TOGGLE_DOCTOR_DETAILS_MODAL: 'TOGGLE_DOCTOR_DETAILS_MODAL',
  UPDATE_ADD_DOCTOR_MODAL_STATE: 'UPDATE_ADD_DOCTOR_MODAL_STATE',
  UPDATE_ACTIVE_USER_ID: 'UPDATE_ACTIVE_USER_ID',
};
